version: "2"

services:
  app:
    image: dmitryrck/ruby
    volumes:
      - .:/app
      - bundle_path:/usr/local/bundle
    environment:
      - BUNDLE_APP_CONFIG=/app/.bundle
      - REDIS_URL=redis://db:6379/1
    working_dir: /app
    command: bundle exec puma -p 3000 config.ru
    ports:
      - "3000:3000"
    links:
      - db

  db:
    image: redis
    expose:
      - "6379"
    volumes:
      - redis:/data

volumes:
  bundle_path:
  redis:
